[package]
name = "save_hoarder"
version = "0.1.0"
authors = ["Michael Bryant <shadow53@shadow53.com>"]
edition = "2018"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = { version = "3.0" }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
toml = "0.5"
