[package]
name = "hoard"
version = "0.1.0"
authors = ["Michael Bryant <shadow53@shadow53.com>"]
edition = "2018"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "3.0.1"
log = "0.4.14"
serde = { version = "1.0.123", features = ["derive"] }
structopt = "0.3.21"
thiserror = "1.0.24"
toml = "0.5.8"

[dev-dependencies]
maplit = "1.0"
rand = "0.8"
tempfile = "3.2"
