[package]
name = "hoard"
version = "0.2.0"
authors = ["Michael Bryant <shadow53@shadow53.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Hoard backups of files across your filesystem into one location."
homepage = "https://github.com/Shadow53/hoard"
repository = "https://github.com/Shadow53/hoard"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { version = "0.2", features = ["ansi"] }
directories = "3.0.1"
hostname = "0.3"
tracing = "0.1"
once_cell = "1.7"
petgraph = "0.5"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3.21"
thiserror = "1.0.24"
toml = "0.5.8"
which = "4.1"

[dev-dependencies]
maplit = "1.0"
rand = "0.8"
serial_test = "0.5"
serde_test = "1.0"
tempfile = "3.2"
