[tasks.clean-all]
    script = """
    cargo clean
    rm -rf profraw
    """

[tasks.install-nightly]
    ignore_errors = true
    command = "rustup"
    args = ["toolchain", "install", "nightly", "--component", "llvm-tools-preview", "--target", "x86_64-unknown-linux-musl"]

[tasks.build-nightly]
    install_crate = false
    dependencies = ["install-nightly"]
    command = "cargo"
    args = ["+nightly", "build", "--target", "x86_64-unknown-linux-musl"]

[tasks.test-nightly]
    install_crate = false
    dependencies = ["install-nightly"]
    command = "cargo"
    args = ["+nightly", "test", "--target", "x86_64-unknown-linux-musl"]
    [tasks.test-nightly.env]
        RUSTFLAGS="-Zinstrument-coverage"
        LLVM_PROFILE_FILE="profraw/hoard-test-%p-%m.profraw"

[tasks.integration-tests]
    dependencies = ["build-nightly"]
    script = """
    mkdir -p ./profraw
    sudo docker image build . -t hoard-tests
    echo "Running tests"
    sudo docker container run --rm -v $(pwd)/profraw:/hoard-tests/profraw:Z hoard-tests
    echo "Ran tests"
    """

[tasks.grcov]
    dependencies = ["test-nightly"]
    install_crate = "grcov"
    command = "grcov"
    args = [
        ".", "-s", ".", "-t", "html",
        "--branch", "--ignore-not-existing",
        "-o", "./target/debug/coverage/"
    ]
    [tasks.grcov.env]
        CARGO_INCREMENTAL=0
        RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
        RUSTDOCFLAGS="-Cpanic=abort"

[tasks.grcov-src]
    dependencies = ["clean-all", "test-nightly", "integration-tests"]
    #install_crate = "grcov"
    script = """
    grcov profraw/*.profraw --binary-path ./target/x86_64-unknown-linux-musl/debug -s . -t html --branch --ignore-not-existing -o ./target/debug/coverage
    """
    #command = "grcov"
    #args = [
    #    "*.profraw",
    #    "--binary-path", "./target/debug",
    #    "-s", ".", "-t", "html",
    #    "--branch", "--ignore-not-existing",
    #    "-o", "./target/debug/coverage/"
    #]
    [tasks.grcov-src.env]
        RUSTFLAGS="-Zinstrument-coverage"
        LLVM_PROFILE_FILE="default.profraw"
        RUSTUP_TOOLCHAIN="nightly"

[tasks.view-grcov-src]
    dependencies = ["grcov-src"]
    command = "xdg-open"
    args = ["./target/debug/coverage/index.html"]

[tasks.view-grcov]
    dependencies = ["grcov"]
    command = "xdg-open"
    args = ["./target/debug/coverage/index.html"]
