[tasks.clean-all]
    script = """
    cargo clean
    rm -rf profraw
    """

[tasks.create-profraw-dir]
    command = "mkdir"
    args = ["-p", "./profraw"]

[tasks.install-stable]
    ignore_errors = true
    command = "rustup"
    args = ["toolchain", "install", "stable", "--component", "llvm-tools-preview", "--target", "x86_64-unknown-linux-musl"]

[tasks.build-stable]
    install_crate = false
    dependencies = ["install-stable"]
    command = "cargo"
    args = ["+stable", "build", "--target", "x86_64-unknown-linux-musl"]
    [tasks.build-stable.env]
        RUSTC_BOOTSTRAP="1"
        RUSTFLAGS="-Zinstrument-coverage"

[tasks.test-stable]
    install_crate = false
    dependencies = ["clean-all", "install-stable", "create-profraw-dir"]
    command = "cargo"
    args = ["+stable", "test", "--target", "x86_64-unknown-linux-musl"]
    [tasks.test-stable.env]
        RUSTC_BOOTSTRAP="1"
        RUSTFLAGS="-Zinstrument-coverage"
        LLVM_PROFILE_FILE="profraw/hoard-cargo-test-%p-%m.profraw"

[tasks.integration-tests]
    dependencies = ["clean-all", "build-stable", "create-profraw-dir"]
    script = """
    sudo docker image build . -t hoard-tests
    echo "Running tests"
    sudo docker container run --rm -v $(pwd)/profraw:/hoard-tests/profraw:Z hoard-tests
    echo "Ran tests"
    """
    [tasks.integration-tests.env]
        RUSTC_BOOTSTRAP="1"
        RUSTFLAGS="-Zinstrument-coverage"
        LLVM_PROFILE_FILE="profraw/hoard-python-test-%p-%m.profraw"

[tasks.grcov]
    dependencies = ["clean-all", "test-stable", "integration-tests"]
    # Using `script` is necessary to get the glob expansion
    script = """
    grcov profraw/*.profraw --binary-path ./target/x86_64-unknown-linux-musl/debug \
        -s . -t html --branch --ignore-not-existing -o ./target/debug/coverage --ignore src/main.rs \
        --excl-br-line "($EXCLUDE_DERIVE|$EXCLUDE_PANICS|$EXCLUDE_TRACING|$EXCLUDE_PROPAGATE_ERROR|$EXCLUDE_MANUAL|$EXCLUDE_LONE_CLOSING_BRACE)" \
        --excl-line "($EXCLUDE_DERIVE|$EXCLUDE_PANICS|$EXCLUDE_TRACING|$EXCLUDE_PROPAGATE_ERROR|$EXCLUDE_MANUAL|$EXCLUDE_LONE_CLOSING_BRACE)" \
        --excl-br-start "(grcov: ignore-start|mod tests)" --excl-start "(grcov: ignore-start|mod tests)" \
        --excl-br-stop "grcov: ignore-end" --excl-stop "grcov: ignore-end"
    """
    [tasks.grcov.env]
        RUSTFLAGS="-Zinstrument-coverage"
        RUSTC_BOOTSTRAP="1"
        RUSTUP_TOOLCHAIN="stable"
        HOARD_LOG="trace"
        EXCLUDE_DERIVE="#\\[derive\\("
        EXCLUDE_PANICS="panic!|todo!|unimplemented!"
        EXCLUDE_TRACING="tracing::(error|warn|info|debug|trace)(_span)?"
        EXCLUDE_PROPAGATE_ERROR="(return|(Err\\(err(or)?\\)|err(or)?) =>) (Some\\()?Err\\(err(or)?(\\.into\\(\\))?\\)"
        EXCLUDE_MANUAL="grcov: ignore"
        EXCLUDE_LONE_CLOSING_BRACE="^\\s*\\}\\s*$"

[tasks.view-grcov]
    dependencies = ["grcov"]
    command = "xdg-open"
    args = ["./target/debug/coverage/index.html"]

[tasks.book]
    command = "mdbook"
    args = ["serve", "./book"]
