exclusivity = [[ "unix", "windows" ]]

[envs]
[envs.unix]
    os = ["linux", "macos"]
[envs.windows]
    os = ["windows"]

[hoards]
[hoards.md5]
    config = { hash_algorithm = "md5" }
    "unix" = "${HOME}/testing.txt"
    "windows" = "{USERPROFILE}/testing.txt"
[hoards.sha256]
    config = { hash_algorithm = "sha256" }
    "unix" = "${HOME}/testing.txt"
    "windows" = "{USERPROFILE}/testing.txt"
[hoards.default]
    "unix" = "${HOME}/testing.txt"
    "windows" = "{USERPROFILE}/testing.txt"

