on: [push]

name: Publish mdBook

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mdBook
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook
          version: latest
          use-tool-cache: true
      - name: Build mdBook
        if: ${{ github.ref == 'refs/heads/33-mdbook' }}
        run: mdbook build book
      - name: Publish to Netlify
        if: ${{ github.ref == 'refs/heads/33-mdbook' }}
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: book/book
          production-branch: main
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
