name: Release

on:
  workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Knope
        uses: knope-dev/action@v1
      - uses: Swatinem/rust-cache@v2
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          knope release
        env:
          GITHUB_TOKEN: ${{ secrets.KNOPE_TOKEN }}
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
